// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD5bJiLeSxuKSGGLRZH4_pZkDHkC0mm9g',
    appId: '1:116601275817:web:1df940ab9aa24a74b5f0b8',
    messagingSenderId: '116601275817',
    projectId: 'uganda-explore',
    authDomain: 'uganda-explore.firebaseapp.com',
    storageBucket: 'uganda-explore.firebasestorage.app',
    measurementId: 'G-J2P79SK915',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlMhem690sa2rqlfDhCL3-0yVcdTHeWYU',
    appId: '1:116601275817:android:87645805792893beb5f0b8',
    messagingSenderId: '116601275817',
    projectId: 'uganda-explore',
    storageBucket: 'uganda-explore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqPbFctWxYO7LqllAImz_1unBjfK_2kz8',
    appId: '1:116601275817:ios:3fbe0167632646eeb5f0b8',
    messagingSenderId: '116601275817',
    projectId: 'uganda-explore',
    storageBucket: 'uganda-explore.firebasestorage.app',
    iosBundleId: 'com.example.ugandaExplore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqPbFctWxYO7LqllAImz_1unBjfK_2kz8',
    appId: '1:116601275817:ios:3fbe0167632646eeb5f0b8',
    messagingSenderId: '116601275817',
    projectId: 'uganda-explore',
    storageBucket: 'uganda-explore.firebasestorage.app',
    iosBundleId: 'com.example.ugandaExplore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD5bJiLeSxuKSGGLRZH4_pZkDHkC0mm9g',
    appId: '1:116601275817:web:13db89a6a6cc0ce4b5f0b8',
    messagingSenderId: '116601275817',
    projectId: 'uganda-explore',
    authDomain: 'uganda-explore.firebaseapp.com',
    storageBucket: 'uganda-explore.firebasestorage.app',
    measurementId: 'G-5C7BTVMGVP',
  );
}
