// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf6b7-B0tFPwrqa6OLiKVNcLZzvvIWj_w',
    appId: '1:73784585693:web:eb2b7b6ba4f43bdba31a34',
    messagingSenderId: '73784585693',
    projectId: 'uganda-explore-935e5',
    authDomain: 'uganda-explore-935e5.firebaseapp.com',
    storageBucket: 'uganda-explore-935e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPclmAk0-g0Keqqom6PdJuS7qGaHXpyaU',
    appId: '1:73784585693:android:2b79bc292afa4f37a31a34',
    messagingSenderId: '73784585693',
    projectId: 'uganda-explore-935e5',
    storageBucket: 'uganda-explore-935e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARiZqb18PmUi7KQBlT0X09d1MBqW99lx0',
    appId: '1:73784585693:ios:c06b9336d9c36a16a31a34',
    messagingSenderId: '73784585693',
    projectId: 'uganda-explore-935e5',
    storageBucket: 'uganda-explore-935e5.firebasestorage.app',
    iosBundleId: 'com.example.ugandaExplore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARiZqb18PmUi7KQBlT0X09d1MBqW99lx0',
    appId: '1:73784585693:ios:c06b9336d9c36a16a31a34',
    messagingSenderId: '73784585693',
    projectId: 'uganda-explore-935e5',
    storageBucket: 'uganda-explore-935e5.firebasestorage.app',
    iosBundleId: 'com.example.ugandaExplore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf6b7-B0tFPwrqa6OLiKVNcLZzvvIWj_w',
    appId: '1:73784585693:web:878cfedadb8d8ca9a31a34',
    messagingSenderId: '73784585693',
    projectId: 'uganda-explore-935e5',
    authDomain: 'uganda-explore-935e5.firebaseapp.com',
    storageBucket: 'uganda-explore-935e5.firebasestorage.app',
  );
}
